name: PushAll

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: node_modules_cache
        with:
          path: |
            ~/.npm
            **/node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build:dev
      - uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,author,message,workflow,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
